### ISSUE TITLE
Example HTML

### ISSUE THREAD

**Issue by dylantuohy** [faktorvier/jquery-video#1]
Hello! Could you please provide an example of the HTML element represented by the '.video' selector?

**Comment by Stibo** [comment]
Hi!

Sorry for the late answer. I've just added a simple demo page for this plugin.

You can find the demo here: http://labs.faktorvier.ch/plugins/jquery-video/demo.html

**Comment by ashrafreda** [comment]
Hi,,
I included the library and this issue appear to me
"Uncaught TypeError: Cannot read property 'config' of null" on the console
