### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by ashrafreda** [faktorvier/jquery-video#2]
Hi,,
I included the library and this issue appear to me
"Uncaught TypeError: Cannot read property 'config' of null" on the console

**Comment by Stibo** [comment]
Hi,
thanks for the feedback! Can you include the unminified library (jquery.video.js) in your project (
instead of the minified file) and tell me on which code-line the error occures? So I can try to figure out what the problem might be.

**Comment by ashrafreda** [comment]
Thanks Stibo for reply
I used your library to control (play and pause) more than video (youtube and vimeo) at the same page,
but I initialize the video with
jQuery(".tie_video_frame").video();
so the issue appeared. but when use each loop:
jQuery(".tie_video_frame").each(function(){
     jQuery(this).video();
});
the issue solved with minified library.

another issue, I built playlist as youtube playlist, I used one iframe and update it's src with video url and want to play the video after the video loaded.
It's possible?

**Comment by Stibo** [comment]
jQuery(".tie_video_frame").video(); appears to be correct...

Can you tell me on which code-line in the **jquery.video.js** file (not your implementation, the library file) the error occurs? Or can you paste me the complete error message (in most developer consoles you can toggle the short message to a larger message)? Or even better: is your code public so i can see the error for myself?

Concerning your other issue: I have never tested this, but have you tried to add an ready event to the video (https://github.com/faktorvier/jquery-video#onready) and checked, if the event triggers even if you change the video url?

**Comment by Stibo** [comment]
I have tested my idea for your playlist-issue and came to this solution (the onReady idea does not work correctly):

Before you change the iframe's src you have to destroy the old video, then set the new src and then reinit the video. The following sample changes the src for a youtube video:

```
$('.video').video('destroy'); // destroy
$('.video').attr('src', '//www.youtube.com/embed/YE7VzlLtp-4'); // change src
$('.video').video(); // reinit
```

I have added a test in our plugin-demo (http://labs.faktorvier.ch/plugins/jquery-video/demo.html, "change video" button). Hope this works for you!

**Comment by ashrafreda** [comment]
Thanks alot Stibo..
this work correctly.
but :)  there is another issue:
the video don't play after the first click and work with any another click

```
jQuery(".tie-video-item").on("click",function(){
    var frame_id = jQuery(this).data("name"),
    this_video_frame = "#" + frame_id;
    video_src = jQuery(this).data("src"),
    frame_current_src = jQuery("#"+frame_id).attr("src"),

    // pause all videos when thum clicked
    jQuery(".tie_video_frame").pauseVideo();

        // if the frame src is empty then load it's frame with it's video src
        if(!frame_current_src){
            jQuery(this_video_frame).video('destroy');
        document.getElementById(frame_id).src = video_src;
        jQuery(this_video_frame).video();
    }

    // if the frame src isn't empty, Just show the frame without updating it's src attr
        jQuery(this_video_frame).fadeIn();

    // at the last, play the video
    jQuery(this_video_frame).playVideo();

})
```

![video](https://cloud.githubusercontent.com/assets/16459340/12179818/b5a3db7a-b581-11e5-8f53-810b7615b38d.PNG)

when click the thumbnail the playing video will pause and the clicked video start in playing (it's what i want). but what's happen: after updating the iframe src with video url this message appear in the console "Player not initialized!" and the video doesn't play, but if i clicked it again it work correctly..

I thought this is the last issue and the playlist work great ..
very thanks again

**Comment by ashrafreda** [comment]
this error appear too:
"Uncaught TypeError: a.playVideo is not a function"
when the updated iframe loaded the first time.

**Comment by Stibo** [comment]
Looks like the video is not correclty reinitialized after the destroy. That explains why a.playVideo is not a function and the message "Player not initialized!". Can you check if the video is correctly initialized after the destroy?

**Comment by ashrafreda** [comment]
in the code above..

```
if(!frame_current_src){
    jQuery(video_id).video('destroy');
    document.getElementById(frame_id).src = video_src;
    jQuery(video_id).video();
}
```

I destroy the video and update src and then reinitialized  the video again,,
There is another method to reinitialized the video other than this:

```
jQuery(video_id).video();
```

**Comment by ashrafreda** [comment]
excuse me,,
can I get the video duration using your library

**Comment by haze83** [comment]
hi ashrafreda,
to autoplay the video after initialization, you have to wait until it's ready... 

``` javascript
if(!frame_current_src) {
    jQuery(video_id).video('destroy');
    document.getElementById(frame_id).src = video_src;
    jQuery(video_id).video();
    jQuery(video_id).addVideoEvent('ready', function(e, $video, video_type) {
        $video.playVideo();
        // get the duration
        var duration = $video.getVideoPlayer().getDuration();
    });
} else {
    // at the last, play the video, even when it's paused
    jQuery(this_video_frame).playVideo();
}
```

in the snippet above you also get the duration of the YouTube video. To prevent the error "Uncaught TypeError: a.playVideo is not a function" you have to put the `jQuery(this_video_frame).playVideo();` in the else part.

**Comment by ashrafreda** [comment]
Very Big thanks haze
All work great..
but the duration doesn't work for vimeo
